# Write your MySQL query statement below
SELECT CONTEST_ID,
ROUND(
COUNT(DISTINCT R.USER_ID) * 100.0 / (SELECT COUNT(*) FROM USERS),
2
) AS PERCENTAGE

FROM 
USERS U
JOIN
REGISTER R
ON
U.USER_ID=R.USER_ID
GROUP BY   R.CONTEST_ID
ORDER BY 
    PERCENTAGE DESC,
    R.CONTEST_ID ASC;